import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Link to="/">
          <Button variant="ghost" className="mb-6 hover:bg-muted">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <div className="prose prose-slate dark:prose-invert max-w-none bg-card p-8 rounded-lg shadow-sm border border-border">
          <h1 className="text-3xl font-bold mb-6">Privacy Policy – pixel-sans</h1>
          <p className="text-sm text-muted-foreground mb-8">Effective date: November 24, 2025</p>

          <p>
            This Privacy Policy explains how <strong>pixel-sans</strong> (“we”, “our”, “the Company”) collects, uses, stores, and protects information when you access our website <strong>pixel-sans</strong> (the “Site”). We are a company based in <strong>Colombia</strong>, and we are committed to respecting your privacy and complying with applicable Colombian data-protection regulations, including <strong>Law 1581 of 2012</strong> and its regulatory decrees.
          </p>

          <p>
            Our website is an informational blog. We do <strong>not</strong> actively collect personal data, we do <strong>not</strong> offer user registration, and we do <strong>not</strong> use analytics services. Only a minimal amount of technical information is processed to operate the Site securely and efficiently.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Information We Collect</h2>
          <p>
            We do <strong>not</strong> ask visitors to provide personal information, nor do we collect personal data through registration forms, analytics tools, or tracking technologies beyond what is strictly necessary.
          </p>
          <p>
            However, when you access or interact with the Site, certain <strong>limited and technical</strong> data may be collected automatically:
          </p>

          <h3 className="text-xl font-medium mt-6 mb-3">1.1 Technical Data</h3>
          <p>We may process:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>IP address (automatically transmitted by your device when accessing the Site)</li>
            <li>Browser type and version</li>
            <li>Device and operating system information</li>
            <li>Basic server logs generated by our hosting providers (AWS EC2 and Vercel) for security and operational purposes</li>
            <li>Essential cookies required for the proper functioning of the website</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">1.2 Comments Section</h3>
          <p>The Site contains an <strong>optional and anonymous</strong> comment section.</p>
          <ul className="list-disc pl-6 mb-4">
            <li>You may comment <strong>without providing personal data</strong>.</li>
            <li>If you choose to enter a name or email, this is entirely optional and not required for publication.</li>
            <li>Any information voluntarily submitted in a comment becomes publicly visible.</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">1.3 Advertising (Non-Personalized)</h3>
          <p>We display <strong>non-personalized</strong> advertisements through <strong>Monetag</strong>.</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Monetag may process technical data such as your IP address and basic device information to deliver non-personalized ads.</li>
            <li>No behavioral profiling or personalized ads are used.</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">1.4 No Uploads</h3>
          <p>The Site does <strong>not</strong> allow users to upload images or files.</p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">2. Legal Basis for Processing (According to Colombian Law)</h2>
          <p>
            Under <strong>Law 1581 of 2012</strong>, we process the limited data described above based on the following legal bases:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Authorization not required</strong> for data that is purely technical, non-identifiable, or necessary for website operation (permitted by Colombian law when used for essential and security purposes).</li>
            <li><strong>Legitimate interest</strong> in maintaining the security, availability, and functionality of the Site.</li>
            <li><strong>Legitimate interest</strong> in moderating comments to prevent spam, abuse, or illegal content.</li>
            <li><strong>Legitimate interest</strong> in showing non-personalized advertising that supports site maintenance.</li>
            <li><strong>Compliance with legal obligations</strong>, including security and fraud-prevention requirements.</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">3. Purposes of Processing</h2>
          <p>Your information is processed only for the following purposes:</p>
          <ol className="list-decimal pl-6 mb-4">
            <li><strong>Operating the Website</strong>: Ensuring proper functioning, performance, and security.</li>
            <li><strong>Comment Moderation</strong>: Allowing users to post anonymous comments and preventing spam or misuse.</li>
            <li><strong>Advertising</strong>: Displaying <strong>non-personalized</strong> advertisements via Monetag.</li>
            <li><strong>Security and Fraud Prevention</strong>: Preventing attacks, unauthorized access, or any activity that could jeopardize the Site.</li>
          </ol>
          <p>
            We do <strong>not</strong> create user profiles, analyze behavior, or use tracking technologies for marketing or personalized content.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">4. Data Retention Periods</h2>
          <p>We retain information only for as long as needed to fulfill the purposes described in this Policy:</p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Server logs</strong>: Typically retained for <strong>up to 6 months</strong>, unless required longer for security investigations.</li>
            <li><strong>Comment data</strong>: Retained indefinitely as part of the public blog record, unless deletion is requested or required.</li>
            <li><strong>Essential cookies</strong>: Stored only for their operational lifespan (usually session-based or short-term).</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">5. User Rights</h2>
          <p>
            In accordance with <strong>Law 1581 of 2012</strong>, you have the following rights over any personal data that may be processed:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Right of Access</strong>: Request to know what data is processed, if any.</li>
            <li><strong>Right of Rectification</strong>: Request correction of inaccurate or incomplete data.</li>
            <li><strong>Right of Deletion</strong>: Request deletion of information when permitted by law.</li>
            <li><strong>Right to Object</strong>: Object to processing based on legitimate interest.</li>
            <li><strong>Right to Portability</strong>: Request a copy of your data in a standard format, when applicable.</li>
            <li><strong>Right to Revoke Consent</strong>: Not generally applicable here due to limited data collection, but available when relevant.</li>
          </ul>
          <p>
            To exercise these rights, contact us at:<br />
            📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a>
          </p>
          <p>Requests will be processed in accordance with Colombian regulatory deadlines.</p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">6. International Data Transfers</h2>
          <p>
            Because our Site uses third-party hosting and advertising providers, your data may be transferred internationally:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Hosting</strong>: AWS EC2 and Vercel may process data on servers located outside Colombia.</li>
            <li><strong>Advertising</strong>: Monetag may transfer technical data to provide non-personalized ads.</li>
          </ul>
          <p>
            All providers implement technical and organizational measures aligned with international standards for data protection and security.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">7. Security Measures</h2>
          <p>
            We implement reasonable technical, administrative, and organizational measures to protect information, including:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>Secure hosting and infrastructure</li>
            <li>Encryption protocols where applicable</li>
            <li>Access controls and authentication</li>
            <li>Monitoring for suspicious activity</li>
            <li>Regular maintenance and updates of our systems</li>
          </ul>
          <p>
            Although no system is completely immune to risks, we strive to maintain industry-standard security and promptly address vulnerabilities.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">8. Cookies</h2>
          <p>The Site uses only <strong>essential or operational cookies</strong>, such as:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Cookies required for navigation or basic functionality</li>
            <li>Cookies used for anonymous comment session management</li>
            <li>Cookies necessary for displaying <strong>non-personalized</strong> ads</li>
          </ul>
          <p>
            We do <strong>not</strong> use tracking cookies, analytics cookies, or behavioral advertising cookies.
          </p>
          <p>
            You may adjust your browser settings to block cookies, but some site functions may be affected.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">9. Children’s Privacy</h2>
          <p>
            The Site is <strong>not directed at minors</strong>, and we do not knowingly collect information from individuals under 18 years of age.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">10. Data Protection Officer (DPO)</h2>
          <p>
            Under Colombian regulations, appointing a Data Protection Officer is <strong>not mandatory</strong> for our type of processing.<br />
            Therefore, <strong>pixel-sans has not designated a DPO</strong>. However, we remain committed to ensuring compliance and transparency.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">11. Contact Information</h2>
          <p>
            If you have any questions regarding this Policy or wish to exercise your rights, contact us at:
          </p>
          <p>
            📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a>
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">12. Changes to This Privacy Policy</h2>
          <p>
            We may update this Policy from time to time to reflect operational or legal changes. Updates will be posted clearly on this page with a revised effective date.
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
