import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Link to="/">
          <Button variant="ghost" className="mb-6 hover:bg-muted">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <div className="prose prose-slate dark:prose-invert max-w-none bg-card p-8 rounded-lg shadow-sm border border-border">
          <h1 className="text-3xl font-bold mb-6">Terms and Conditions of Use – pixel-sans</h1>
          <p className="text-sm text-muted-foreground mb-8">Effective date: November 24, 2025</p>

          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            Access to and use of the website <strong>pixel-sans</strong> (“the Site”) implies full acceptance of these <strong>Terms and Conditions</strong> (“T&C”). If you do not agree with them, you must refrain from using the Site.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">2. Purpose and Scope</h2>
          <p>
            <strong>pixel-sans</strong>, based in Colombia, is an <strong>informational blog</strong> that publishes articles, reviews, and digital content. The Site does not offer individualized professional advice, personalized services, nor does it establish a contractual relationship with users beyond the acceptance of these T&C.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">3. Access and Use of the Site</h2>
          <ul className="list-disc pl-6 mb-4">
            <li>Access to the Site is free and does not require registration.</li>
            <li>There are no contact forms or file upload mechanisms.</li>
            <li>The owner may <strong>suspend, limit, or block</strong> access to users who misuse the Site, affect its operation, or violate these T&C.</li>
            <li>The Site is hosted and deployed on <strong>EC2 and Vercel</strong>, managed directly by the owner.</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">4. Comments and Rules of Conduct</h2>
          <p>
            Users may publish comments, including <strong>anonymous</strong> comments, under their sole responsibility.
          </p>

          <h3 className="text-xl font-medium mt-6 mb-3">4.1 Mandatory Rules of Conduct</h3>
          <p>It is strictly prohibited to publish comments that:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Include <strong>hate speech, discrimination, pornography, threats, defamation, or slander</strong>.</li>
            <li>Contain <strong>illegal content</strong>, including instructions for committing crimes.</li>
            <li>Publish <strong>personal data of third parties</strong> without authorization.</li>
            <li>Are intended for <strong>spam, unsolicited advertising, phishing</strong>, identity theft, or redirection to malicious sites.</li>
            <li>Attempt to manipulate, sabotage, or destabilize the Site.</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">4.2 Moderation</h3>
          <p>
            The owner reserves the right to <strong>moderate, edit, hide, or delete</strong> comments that violate these rules or the law, without obligation to justify each case.
          </p>

          <h3 className="text-xl font-medium mt-6 mb-3">4.3 Reports</h3>
          <p>
            If you detect a comment that violates these rules, you can report it by writing to 📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a> with the URL and description of the problem.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Intellectual Property</h2>
          <ul className="list-disc pl-6 mb-4">
            <li>Unless expressly stated, the <strong>texts and publications</strong> of the Site —including those generated by AI— are the property of <strong>pixel-sans</strong>.</li>
            <li><strong>Reading, quoting, and referencing</strong> the content is permitted, provided that the source is clearly indicated (“pixel-sans”) and a link to the original article is included.</li>
            <li><strong>Prior written authorization</strong> is required to reproduce the content in full, store it massively, redistribute it, or use it for commercial purposes.</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">5.1 Images and Third-Party Content</h3>
          <ul className="list-disc pl-6 mb-4">
            <li>Some thumbnails or images on the Site come from <strong>public YouTube thumbnails</strong> or may be generated by AI.</li>
            <li>These contents may be subject to <strong>third-party copyright</strong>.</li>
            <li>The owner does not guarantee absolute ownership of such materials and does not authorize their reuse beyond the use permitted by law.</li>
          </ul>

          <h3 className="text-xl font-medium mt-6 mb-3">5.2 Warning</h3>
          <p>
            Unauthorized reproduction of the content may generate <strong>civil and/or criminal liability</strong>, in accordance with Colombian legislation.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">6. Links to Third Parties</h2>
          <p>
            The Site may contain links to external sites.<br />
            <strong>pixel-sans</strong> does not control or guarantee the content, security, or availability of such sites and is not responsible for damages or losses derived from their use.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">7. Advertising and Third-Party Services</h2>
          <ul className="list-disc pl-6 mb-4">
            <li>The Site displays <strong>third-party advertising managed by Monetag</strong>.</li>
            <li>The ads are <strong>NON-personalized</strong>.</li>
            <li>Responsibility for the content, accuracy, and legality of the ads lies exclusively with the <strong>advertisers or third parties involved</strong>.</li>
            <li>The owner does not guarantee the products or services advertised and is not responsible for damages derived from their viewing or access.</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
          <p>Given that the Site is an informational blog:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>The owner does not guarantee the accuracy, completeness, or timeliness of the content.</li>
            <li>The Site is offered “<strong>as is</strong>” and “<strong>as available</strong>”.</li>
            <li>The owner shall not be liable for <strong>indirect damages</strong>, loss of information, damages for use or inability to use, lost profits, or similar damages.</li>
            <li>As users do not make payments to access the Site, the total liability of the owner regarding any claim is limited to the reasonable and non-monetized use of the Site.</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">9. Anti-Fraud Measures and Prohibitions</h2>
          <p>Users agree NOT to:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Engage in fraudulent activities, impersonation, phishing, social engineering, or scams.</li>
            <li>Attempt to access Site systems or servers without authorization.</li>
            <li>Perform denial of service (DDoS) attacks, code injection, vulnerability exploitation, or similar.</li>
            <li>Use bots, scrapers, massive or automated data extraction tools.</li>
          </ul>
          <p>
            Non-compliance may result in <strong>immediate blocking</strong>, reporting to authorities, and legal action.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">10. Indemnification</h2>
          <p>
            The user agrees to <strong>indemnify and hold harmless</strong> <strong>pixel-sans</strong> from any claim, damage, loss, or cost (including legal fees) derived from the breach of these T&C or the misuse of the Site.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">11. Procedure for Intellectual Property Infringement Reports</h2>
          <p>
            To report a possible infringement, send an email to 📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a> with the following information:
          </p>
          <ol className="list-decimal pl-6 mb-4">
            <li>Identification of the claimant and contact details.</li>
            <li>Description of the allegedly infringed work.</li>
            <li>Exact URL of the questioned content on the Site.</li>
            <li>Reasonable proof of ownership (screenshots, official links, registrations, etc.).</li>
            <li>Declaration under penalty of perjury that the information is true and that you have rights to the work.</li>
            <li>Clear request for removal or restriction of the content.</li>
          </ol>
          <p>
            The owner may require additional information and will act <strong>in good faith</strong>, evaluating the case and removing or blocking the content when appropriate.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">12. Privacy</h2>
          <p>
            The processing of personal data —minimal and limited— is described in the <strong>Privacy Policy</strong> available on the Site.<br />
            To exercise data protection rights, write to 📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a>.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">13. Duration, Modification, and Termination</h2>
          <ul className="list-disc pl-6 mb-4">
            <li>These T&C will be in effect as long as they remain published on the Site.</li>
            <li>The owner may modify them at any time by publishing the updated version and new effective date.</li>
            <li>Use of the Site after the publication of modifications implies acceptance thereof.</li>
            <li>The owner may suspend or terminate access to users who violate these T&C or engage in illegal or abusive acts.</li>
          </ul>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">14. Applicable Law and Jurisdiction</h2>
          <p>
            These T&C are governed by <strong>Colombian legislation</strong>.<br />
            Any dispute will be resolved by the <strong>competent courts and tribunals of Colombia</strong>.
          </p>

          <hr className="my-8" />

          <h2 className="text-2xl font-semibold mt-8 mb-4">15. Final Clause</h2>
          <p>
            These Terms and Conditions regulate the use of the blog <strong>pixel-sans</strong>. If you have questions or require clarification, you can write to 📧 <a href="mailto:contacto@pixel-sans.com" className="text-primary hover:underline">contacto@pixel-sans.com</a>.<br />
            We invite you to use the Site in a respectful, responsible manner and in accordance with the law.
          </p>

          <hr className="my-8" />

          <p className="text-sm text-muted-foreground mt-8">Effective date: November 24, 2025</p>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
